//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksManagementSystem
{
    public partial class Title_Author
    {
        public int AU_ID { get; set; }
        public string ISBN { get; set; }
    }
}